#!/bin/sh
#
# Publish contents in html-pub branche to deply directory,
# just like gh-pages branch as to GitHub.
#
# To enable this hook, rename this file to "post-update".

# Do git-update-server-info for git dumb protocol.
dumb=$(git config --bool hooks.update-server-info || echo "false")
if [ "$dumb" = "true" ]; then
    git update-server-info
fi

LOCATION=.LOCATION
DEPLOY=/var/lib/gitolite/deploy

while [ $# -gt 0 ]; do
    case "${1#refs/heads/}" in
    html-pub)
        target=$(git show $1:$LOCATION 2>/dev/null || echo "")
        if [ -n "$target" ]; then
            target=${target#/}
            target=$DEPLOY/$target
            mkdir -p "$target"
            echo >&2 "checkout to $target..."
            git --work-tree="$target" reset --hard $1
        else
            echo >&2 "File '$LOCATION' not found in branch '${1#refs/heads/}'."
        fi
        break
        ;;
    esac
    shift
done
