#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

dumb=$(git config --bool hooks.update-server-info || echo "false")
if [ "$dumb" = "true" ]; then
    git update-server-info
fi

BRANCH=refs/heads/html-pub
LOCATION=.LOCATION
LOCATION2=LOCATION

while [ $# -gt 0 ]; do
    if [ "$1" = "$BRANCH" ]; then
        target=$(git show $BRANCH:$LOCATION 2>/dev/null || git show $BRANCH:$LOCATION2 2>/dev/null || echo "")
        if [ -n "$target" ]; then
            mkdir -p $target
            echo >&2 "checkout to $target..."
            git --work-tree="$target" reset --hard $BRANCH
        else
            echo >&2 "File '$LOCATION' not found in branch '${BRANCH##*/}'."
        fi
    fi
    shift
done
